version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - absensi

  database-attendance:
    container_name: database-attendance-container
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - absensi

networks:
  absensi:

volumes:
  pgdata: